### PR TITLE
Add French language

### PR DESCRIPTION
**Pull request by DaliaAsTrue**

### CODE REVIEW

**Comment by ar-x** [comment]
@DaliaAsTrue This is super. Can you find someone from our community to review the language (as noted by (6) in the README). Once thats done, we'll ship this. Thanks!

**Comment by ar-x** [comment]
@DaliaAsTrue To confirm, this is ready to go and there is nothing to be improved on it?

**Comment by DaliaAsTrue** [comment]
@ar-x With my Discord we corrected somes points, now it's good !

**Comment by romromna** [comment]
I finished reviewing it guys. very good. Just some minor things to change.

1-"Informations diverses sur les Turtle" no you re talking of several turtles so put "Turtles"

2-"minage de Minero auquel vous êtes habitués" I guess you meant "Monero" there?

3-"les portefeuilles suivantes": No "suivant"

4-"Qu'est ce qui est bien avec un ATM s'il n'est pas à proximité ? Touchez-et-payez, c'est du passé ; Touchez-et-gagnez, c'est l'avenir. Votre Crypto ATM se trouve dans votre poche."

"ATM"? no. this does not mean anything to french speaking people. "point de retrait" is where you withdraw cash from in the streets. I guess this is what you could put for "ATM"

**Comment by ar-x** [comment]
@romromna Let me know once you are all satisfied (and @DaliaAsTrue too), and we'll merge this one in. Thanks!

**Comment by romromna** [comment]
Yes, good now :).

**Comment by ar-x** [comment]
@romromna Super! @DaliaAsTrue I'll merge it in once you give me a 👍

**Comment by ar-x** [comment]
Thanks for your work on this. French is going to be the first language to be deployed. I'll let you know once we've rolled it out.

cc @RocksteadyTC

**Comment by ar-x** [comment]
@DaliaAsTrue @romromna @SaintePelle  – I've deployed a preview of the site at – https://gaara-38.shadow-clone-jutsu.com/. Can see if it looks ok. Thanks.

**Comment by ar-x** [comment]
never mind, i'll ping you for review once its deployed to production.

**Pull request merged**
